### ISSUE TITLE
SQL query to clean harvester

### ISSUE THREAD

**Issue by mil00se** [ckan/ckanext-harvest#105]
Hello,

I have 2 questions about SQL queries used to clean (I see those queries in the file  ckanext/harvest/logic/action/update.py).

Why do you delete in this order  "package_role" and then "user_object_role" ?
In my case, the sub-query 

select user_object_role_id from package_role 

returns more than 5 000 000 entities and I want to clean only 1700 datasets.
If we just invert the deletion, like this

delete from user_object_role where id in (select user_object_role_id from package_role where package_id in (select id from package where state = 'to_delete' )) and context = 'Package';
delete from package_role where package_id in (select id from package where state = 'to_delete' );

the result will be faster?!?!

My other question is about the last query :

delete from package where id in (select id from package where state = 'to_delete');

why don't you simply do like this :

delete from package where state = 'to_delete';

best regards
Antoine

**Comment by florianm** [comment]
@davidread is package_role still referenced in [harvest_source_clear](https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/logic/action/update.py#L149)? My 2.5.0a master with latest ckanext-harvest master tries to delete from this no more existing table.

Should L149 be executed only for CKAN <2.0 along the lines of [L123 ff.](https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/logic/action/update.py#L123)?

**Comment by davidread** [comment]
@florianm thanks for spotting that and yes that sounds like the best way to fix. Would you mind doing a PR?
