### ISSUE TITLE
Run jobs straight away

### ISSUE THREAD

**Issue by davidread** [ckan/ckanext-harvest#111]
When you create a harvester it is a problem that the harvest doesn't run straight away. You have to wait up to 15 minutes for the 'harvester run' cron to run. This means you do something else and often forget to attend to it again for hours. This makes fixing issues with the harvest source a painfully slow process.

I believe that the reason there the harvests are spaced by 15 minutes in the original design was because of the fear that a harvest source could get run twice in parallel, and get in a mess. Recently @amercader added into the 'harvest run' a check to see if a job has finished. Since this is now recorded we do not need to wait for the 15 minute cron - we can start a job when it is created, in the knowledge that a job can't start until the previous one for the source has completed. This simply means putting the job on the gather queue straight away. 'harvest run' will still be used for running scheduled jobs.

**Comment by neothemachine** [comment]
+1 I have my cronjob set to run every 1min just to workaround that.

**Comment by davidread** [comment]
I've created a PR for this - perhaps @neothemachine you might give it a try?

**Comment by neothemachine** [comment]
@davidread Sure, how do I do that most easily? If I clone your branch into a separate folder `ckanext-harvest-test`, is it enough to do `python setup.py develop` in it? Will that remove the link to the `ckanext-harvest` folder that's in use now?

**Comment by davidread** [comment]
@neothemachine I /think/ that will work. Otherwise in your existing ckanext-harvest repo do the usual git dance (assuming origin is not pointing at a fork): 

    git fetch origin
    git checkout -b immediate-harvest origin/immediate-harvest
