### ISSUE TITLE
remove references to obsolete ResourceGroup

### ISSUE THREAD

**Issue by florianm** [ckan/ckanext-harvest#114]
Using ckanext-harvest master on CKAN master (2.3a), clearing imported datasets from a harvest job will fall over now obsolete references to `ResourceGroup`.

`logic/action/update.py`l116ff contains [references](https://github.com/ckan/ckanext-harvest/blob/623daa72c4a5b0f0f3f4796f1dbed44049b34043/ckanext/harvest/logic/action/update.py#L116) to the now obsolete ckan model ResourceGroup.

Could be implemented along [these lines](https://github.com/ckan/ckanext-qa/pull/8/files) by toggling the lines referencing db table `resource_group` depending on whether ResourceGroup can be imported.

**Comment by davidread** [comment]
This was merged, closing.
