### ISSUE TITLE
Creating remote orgs does not work

### ISSUE THREAD

**Issue by metaodi** [ckan/ckanext-harvest#120]
From the ckan-dev mailing list:

> Hello all,
>
> I'm trying to import datasets from a remote CKAN 2.2 instance, and I would like to import owner organizations as well. According to the harvester docs, it should be possible (and fairly easy) to do so using the remote_orgs:"create" configuration. However, after doing some tests, no organization is being imported.
>
> Looking at the code, the remote organizations are being fetched using the /group route of the v2 of the API. But testing the api/2/rest/group/ with Postman, I can see it only returns a list of ids from groups, not organizations.
>
> I believe that's the reason why the harvester can't find the owner_org. 
> Is this a known bug? Should api/2/rest/group/ return organization ids too or is what I'm getting expected behavior?
>
> In case the latter is true, should we change CKANHarvester to use v3 of the api and /organization_show ? Or is there a better workaround?
>
> Thanks for your help in advance.
> Cheers,
>
> Rodrigo Parra

I could verify this behaviour. A call to /api/2/rest/group used to return organization as well, but now this is not the case anymore so the creating of remote organizations is broken.

**Comment by davidread** [comment]
Whatever has happened, it would be good for this call to be updated to use the v3 API call in the first instance.

However there is a bit of a curse on the CKAN Harvester because people need it to harvest from CKANs of all versions. i.e. I think we need to keep it working for any old CKANs, pre v3 API. So a fall-back to the rest call is needed.

**Comment by metaodi** [comment]
I added the fallback to my PR.
