### ISSUE TITLE
readme.md does not mention the 'harvest' user  must be created 

### ISSUE THREAD

**Issue by bauerpy** [ckan/ckanext-harvest#127]
When the remote organization or group will be create, on ckanext-When the remote organization or group will be created, on ckanext-harvest/ckanext/harvest/harvesters/ckanharvester.py on the context object the user used is 'harvest', but in the manual does not specified that.

Can add this step in readme.md?

**Comment by amercader** [comment]
This was a remnant of previous CKAN versions. I've added some changes so that is no longer necessary to create the `harvest` user (an internal one will be used). Thanks for flagging this up.
