### ISSUE TITLE
mysite.ini error

### ISSUE THREAD

**Issue by badbruce07** [ckan/ckanext-harvest#128]
Hey good afternoon,
Earlier I was trying to setup ckanext-harvester and then I got to step 4 where I should run `paster --plugin=ckanext-harvest harvester initdb --config=mysite.ini` and it returned `AssertionError: Config filename '/usr/lib/ckan/default/src/ckanext-harvest/mysite.ini' does not exist`. This was after I did the previous 3 steps. How do I resolve such a problem?

**Comment by metaodi** [comment]
@badbruce07 Do you have a config file? [See the documentation how you can create it](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#create-a-ckan-config-file). After that you have to make sure to use the correct path to that config file (`[...] -c /path/to/my/mysite.ini`)

**Comment by badbruce07** [comment]
It's fine. I actually got it resolved now. I realised what went wrong and I got the setup to work.

**Comment by davidread** [comment]
@badbruce07 close the issue next time, thanks.
