### ISSUE TITLE
Packages deleted by ckan harvester job

### ISSUE THREAD

**Issue by ykhadilkar-rei** [ckan/ckanext-harvest#130]
Is there any way to find packages deleted by harvester job? In harvest_object table package_id column is empty for all deleted packages.

**Comment by davidread** [comment]
I guess it depends on the harvester as they can all do deleting differently. In ckanext-spatial the harvest_object for deleting should contain the package_id:

        for guid in delete:
            obj = HarvestObject(guid=guid, job=harvest_job,
                                package_id=guid_to_package_id[guid],
                                extras=[HOExtra(key='status', value='delete')])
