### ISSUE TITLE
How to stop job?

### ISSUE THREAD

**Issue by CarlQLange** [ckan/ckanext-harvest#131]
So my harvester is in a limbo state. It's running, no matter what I do, but it's not actually doing anything. I've rmsourced, dataset purged, even rebooted, but nothing seems to kill this job.  I would like to completely clear my harvesters - no sources, no jobs, no nothing, in order to get a clean retry at this. Could you help?

Cheers!

**Comment by CarlQLange** [comment]
OK, I finally did this manually by going into the database and clearing the harvest_* tables. No fun though.

**Comment by davidread** [comment]
Yes, it is all too easy to end up with the HarvestJob or its HarvestObjects in a running state when the harvest excepts or is aborted, and so it remains in limbo. I've been doing work on my branch to close down these issues when I spot them and at some point will offer them back as a PR.

**Comment by davidread** [comment]
And I also have a paster command to abort a limbo job, which is the other part of your issue.

If you're keen, you could pick it out of my changes:
https://github.com/ckan/ckanext-harvest/compare/master...datagovuk:2.0

**Comment by amercader** [comment]
You can also Clear all current jobs, objects and datasets for a source clicking the "Clear" button on the source Manage section. IIRC this is not available from the command line (`paster harvester ...`) but it should be really easy to expose.

![y3xj0bq](https://cloud.githubusercontent.com/assets/200230/7584974/5dad79a8-f899-11e4-92b1-235d03dfa43a.png)

**Comment by davidread** [comment]
Clear is now added to the CLI: https://github.com/ckan/ckanext-harvest/pull/134
which is enough for this issue.
