### ISSUE TITLE
Update stable branch?

### ISSUE THREAD

**Issue by metaodi** [ckan/ckanext-harvest#133]
From the README the master branch of this repo should be used to target the current CKAN master. This means, that for CKAN 2.3 the stable branch of ckanext-harvest should be used.

But unfortunately, this does not work because ead9e67a3317739d7f3968aad703452f455e7608 is not on the stable branch (among others), which prevents the proper functionality to work with CKAN 2.3.

Are there any plans to update the stable branch any time soon? Or should I use the master branch from now on?

**Comment by amercader** [comment]
Sorry for the confusion, I think that to avoid confusion we could always target master, as we recently did with ckanext-spatial (https://github.com/ckan/ckanext-spatial/commit/020a2570d2301e7735c5925462ebcb77fcf4b18d).

The reality is that there hasn't been a need for different branches for different CKAN versions, even if we need to add code that handles different versions. `stable` was essentially master but kept getting outdated. 

We should keep the branches up to date in case someone is using them, but tell users to use master. I'll update the docs to reflect this.

**Comment by amercader** [comment]
Done in 84126bb, and updated stable and release-v2.0
