### ISSUE TITLE
Queue name for RabbitMQ broken

### ISSUE THREAD

**Issue by metaodi** [ckan/ckanext-harvest#136]
Unfortuntely the "dynamic" name of the queues introduced in 9f8aae3a1845a0dea16baa3e4b0037d3e0cd85c8, has been fortgotten in the harvester command, hence this now fails with an ugly RabbitMQ error that there is no queue called `ckan.harvest.gather`.

**Comment by amercader** [comment]
Sorry @metaodi you are absolutely right. I've pushed a fix for this (88d9ba0), let me know if it works for you

**Comment by metaodi** [comment]
@amercader That works for me. Thanks for the quick fix :smiley:
