### ISSUE TITLE
Change timezone of displayed dates

### ISSUE THREAD

**Issue by metaodi** [ckan/ckanext-harvest#138]
Is there a way to easily adjust the offset in hours for all the datetimes that the harvester show in the frontend?
As far as I know, all dates are saved with UTC timezone and also displayed that way. This regularly leads to confusing for admins that are not aware of this (we're currently at UTC+2).

Is there an easy fix for that?

**Comment by davidread** [comment]
I don't know of a timezone setting. It'd definitely be useful, ckan-wide, if you'd like to add it. I'm pretty sure that's why dates are all saved as UTC.

Harvesting is one key place, you're right. Also displaying Last Updated / Created fields and in Activity Stream.

**Comment by metaodi** [comment]
It would be nice to have this setting ckan-wide, I just added this issue here, as this is currently the one place where it bothers our users the most. Harvesters are normally time-controlled and hence they'd like to know when happend what, also to cross-reference with web server logfiles that might be in the local time.

**Comment by davidread** [comment]
I've added it in core ckan too: https://github.com/ckan/ckan/issues/2494. Please do contribute it if you have a need - shouldn't be hard to add it to the central helper function that displays dates.

**Comment by davidread** [comment]
This was merged, so closing the issue.
