### ISSUE TITLE
Add extension to CheeseShop / PyPI

### ISSUE THREAD

**Issue by raphaelstolt** [ckan/ckanext-harvest#149]
Wondering why this extension isn't available via the `CheeseShop`. Would _massively_ ease the usage in project requirements.

**Comment by davidread** [comment]
@raphaelstolt we can add it to pypi, but I'm not sure it helps much, since we use a pip-requirements.txt for the dependencies, rather than putting them in the setup.py, so you'd need to install those manually after you pip installed it anyway. What do you think, is it still worth it?

**Comment by raphaelstolt** [comment]
@davidread Why not load the dependencies from the pip-requirements.txt via:
```python
with open('pip-requirements.txt') as f:
    required = [line.strip() for line in f]

...

setup(
  ...
  install_requires=required,
  ...
)
```
IMHO __it should be__ in the CheeseShop / PyPI, though we're currently manually building a wheel distribution that gets stored in the depending repository. But feel free to close the ticket it if you don't see an advantage for the CKAN community.

**Comment by davidread** [comment]
We don't put the requirements in setup.py because then CKAN won't load if you install other requirements. Having them installed separately allows you to install whatever version you like if you choose.

I was simply wondering what you meant by:

> Would /massively/ ease the usage in project requirements.

(your emphasis) when I believe it would simply alter one command from:

    (pyenv) $ pip install -e git+https://github.com/ckan/ckanext-harvest.git#egg=ckanext-harvest

to:

    (pyenv) $ pip install -e ckanext-harvest

**Comment by raphaelstolt** [comment]
Might have exaggerated a bit back than :blush:. I can recall we had to set a few Git config values prior to be able to pull the extension from GitHub, which would have been unnecessary if the extension would have been on PyPi.

**Comment by davidread** [comment]
Ok, thanks for helping clarify this.

If we put it on pypi we also have to worry about doing regular releases, writing changelog etc and I'm not sure there is the will to do that properly.

So on balance I think I'll close this after all.
