### ISSUE TITLE
Migrate the CKAN harvester to use the v3 API

### ISSUE THREAD

**Issue by rossjones** [ckan/ckanext-harvest#157]
To enable extra functionality to more easily be added (such as filters) we should move the CKAN harvester to use v3 of the API which exposes more search functionality.

**Comment by rossjones** [comment]
The PR is at https://github.com/ckan/ckanext-harvest/pull/158

There's an issue where outside the harvester there's a key lookup for extras which fails because of package_search promoting them to top level keys - I am not sure how this will affect how packages are created locally. Any suggestions would be welcome....

**Comment by MrkGrgsn** [comment]
#158 has already been merged. @rossjones can this be closed or does the issue you mention above still exist?

**Comment by rossjones** [comment]
Yes, I believe so.
