### ISSUE TITLE
Deleted harvest source persists in database

### ISSUE THREAD

**Issue by LondonAppDev** [ckan/ckanext-harvest#175]
When I remove a harvest source in the CKAN web interface I noticed that it deletes it from `package` but not the `harvest_source` table.

I wanted to ask if this is by design or is something going wrong?

**Comment by lukecampbell** [comment]
I've observed the same issue :+1:

**Comment by davidread** [comment]
Yup, if you click delete in the web ui then it changes the harvest_source.state to deleted. It could be activated again, but I'm not sure the UI is there to find it again. Maybe someone could check.

**Comment by LondonAppDev** [comment]
Hi David. You can see it in `Trash` in /ckan-admin however you cannot return it to the harvest source list. If the plan is to make a UI for it then it makes sense to keep it I suppose.

**Comment by davidread** [comment]
So there isn't a way to undelete harvest sources, but you can simply create a new one I believe.
