### ISSUE TITLE
Email admins when harvest fails

### ISSUE THREAD

**Issue by davidread** [ckan/ckanext-harvest#185]
This appears to be implemented by the US team (props @yaditi):

https://github.com/ckan/ckanext-harvest/compare/stable...GSA:2.3-upgrade#diff-b14f3f9793a50861d8d323e1cf51123bR370

It would be great to have this in core for the benefit of everyone - what do people think?

**Comment by davidread** [comment]
@amercader is encouraging, as long as it's optional.

Consider per-source config to send emails always, when broken or never. Consider tying this into the 'follow' stuff already in CKAN.

**Comment by earthquakesan** [comment]
@davidread: the government portal we are working on (Leipzig city) is dealing with quite a number of harvesting job. Some of them are long running and manually check when they are over is not really cool.

Imo, community will benefit from the feature as emailing harvest_job creator when it's done.

**Comment by davidread** [comment]
Great to hear it @earthquakesan . My concern about merging this work is that it will generate emails that whilst helpful for many, other recipients will want to opt-out and they won't be able to. data.gov doesn't use a web-form so all their users are focussed on harvesting, but that's not true for most other sites.

So I imagine we need to extend the concept of a user 'following' a dataset to 'followers' of a harvester. And editors/admins of an organization would be set to follow a harvester when it is created, and the emails have a footer with a link to 'unfollow' and stop the emails. It would be great if anyone has a chance to take this on.

**Comment by earthquakesan** [comment]
@davidread so, as I see it:
1. Make "Follow" button for harvest jobs which adds users (admins) to the user_following_harvest_job table
2. Refactor [https://github.com/GSA/ckanext-harvest/blob/809d6888aa1e7baa614ed16611df64b2f6ae604f/ckanext/harvest/logic/action/update.py](commit you mentioned originally) into a separate notification python module
3. Change the logic [https://github.com/GSA/ckanext-harvest/blob/809d6888aa1e7baa614ed16611df64b2f6ae604f/ckanext/harvest/logic/action/update.py#L459](for selecting emails) to get them from the user_following_harvest_job table

Did I understand you correctly?

**Comment by davidread** [comment]
@earthquakesan yes I think you've got a good plan here.

> 1. Make "Follow" button for harvest jobs which adds users (admins) to the user_following_harvest_job table

Yes, although I'd imagine you'd follow a harvest source rather than just a particular job. That would cover both the use case of getting the first harvest (job) to work, and also the when the harvest fails some time in the future (the emphasis should be on automatic/regular harvests, rather than one-offs).

And I'd say that it is important that the organization admin/editors that sets up the harvest source should automatically be set to follow it automatically. Perhaps if the user that sets up the harvest source is from the organization then they would be set to follow it. Whereas if a sysadmin sets it up then maybe he/she plus all the admin/editors for the org are set to follow it. Or maybe that can be configured? This is the area that I find the toughest to understand, since sometimes admin/editors want to be heavily involved in the harvest and sometimes they are purely interested in using the web form to enter datasets.

> 2. Refactor logic from update.py for sending emails into a separate notification python module

That sounds really good. A general way that bits of CKAN can send users notification emails, with an unsubscribe link. There is the basis for this in ckan/lib/mailer.py, currently used for password reset emails. That is a bit of a special case that you can't opt out of those sorts of emails, but would be good to make use of _mail_recipient if possible.

> 3. Change the logic for selecting emails to get them from the user_following_harvest_job table

Nice one.

**Comment by metaodi** [comment]
I'd really appreciate if this feature would be integrated in ckanext-harvest. This is a recurring requirement that we get a lot from our clients (Swiss Federation, City of Zurich, different universities), which make heavy use of harvesters.

@earthquakesan are you planning to implement this?  Let me know if you need help to implement this.
