### ISSUE TITLE
Allow bulk deletion of all datasets when deleting a source

### ISSUE THREAD

**Issue by amercader** [ckan/ckanext-harvest#20]
Note: this targets 2.1

This needs some thought as there are some issues:

* How to efficiently get all ids from the datasets that need to be deleted, via a) search or b) db. a) implies that we need to query for the full dict on potentially lots of datasets when we only need the id. b) would mean go through the harvest object table, as in https://github.com/okfn/ckanext-harvest/blob/release-v2.0/ckanext/harvest/logic/action/get.py#L90

* The  bulk_update_* functions in CKAN core require an organization

* We will maybe need a bulk_update_activate function

* On the frontend, the confirmation message should add a checkbox to select deleting all datasets. Current implementation of the confirm-action module does not allow this, so we either extend it or have a custom one in the harvest extension (probably easier)

/cc @kindly

**Comment by metaodi** [comment]
@amercader  Is this solved with the "clear" functionality?

**Comment by davidread** [comment]
Closing, as it sounds like 'clear' will do this job. Reopen if necessary.
