### ISSUE TITLE
Inconsistent report_status keys

### ISSUE THREAD

**Issue by davidread** [ckan/ckanext-harvest#205]
`HarvestObject.report_status` can take values:

    'added', 'updated', 'not modified', 'deleted', 'errored'

When you look at a job (`harvest_job_show`, `harvest_job_list`, `harvest_source_show_status['last_job']`) it can report the 'stats' - counts of the job objects' report_statuses - which are returned using the same keys. (Uses `harvest_job_dictize()`)

However `harvest_source_list` and `harvest_source_for_a_dataset` has a `source['status']['last_harvest_statistics']` (Uses `harvest_source_dictize`) but returns slightly different keys:

    'added', 'updated', 'errors', 'deleted'

('not modified' has not been added and 'errors' instead of 'errored')

@metaodi and I think we should make them consistent. We discussed this breaking change on https://github.com/ckan/ckanext-harvest/pull/200. I said:

> I don't think anything is done with the job stats, apart from displayed, so maybe it's ok to change. Do you think extensions would use them? Were you looking at the stats when you thought to do #192?

He said:

> Well, we're building a WordPress extension as an "admin interface" for harvesters. So yes, we are consuming and using the API and therefore noticed these inconsistencies.
That said, I think it would be great to be consistent and I frankly think there are not a lot of extensions using the harvester API. At least not enough to not change this. What's your impression?

I agree that there is likely hardly any use of the report_status so far, so it is well worth us making it consistent.

Furthermore, the 2 logic functions which return `errors` are ripe for change anyway:

    harvest_source_list - TODO: Use package search
    harvest_source_for_a_dataset - TODO: Deprecated, harvest source id is added as an extra to each dataset

So those are both going to go anyway. They both are the only callers of `harvest_source_dictize` which is marked `TODO: Deprecated` and that is the only caller of `_get_source_status` which is marked `TODO: Deprecated, use harvest_source_show_status instead`

Indeed we see from the after_show() method that the Package has the `status` key added:

    data_dict['status'] = p.toolkit.get_action('harvest_source_show_status')(context, {    'id': source.id})

which will have the key 'errored'. i.e. the key 'errored' will go when these TODOs are done anyway.

So let's just fix it now shall we?

`harvest_source_list` always returns `'last_harvest_statistics': {'added': 0, 'updated': 0, 'errors': 0, 'deleted': 0}` because it doesn't fill in the values because it sets context['detailed'] to False. So we can just get rid of 'last_harvest_statistics' key.

`harvest_source_for_a_dataset` can just be deleted completely now.

Does that seem reasonable @metaodi and @amercader ?

**Comment by metaodi** [comment]
Yes, this sounds very good. Thanks for the nice summary. :+1:

**Comment by amercader** [comment]
This all makes perfect sense, merged.
It actually will break stuff on the old Genshi templates but I think it's about time we get rid of them: #214

**Comment by amercader** [comment]
Thanks for the thorough investigation @davidread and @metaodi !
