### ISSUE TITLE
Action 'harvest_source_show_status' not found

### ISSUE THREAD

**Issue by smotornyuk** [ckan/ckanext-harvest#227]
This error appears sometimes after adding new source and restarting server.
[After this](https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/model/__init__.py#L521) call activated harvester's [after_view](https://github.com/datawagovau/ckanext-harvest/blob/master/ckanext/harvest/plugin.py#L89).  Action list at this moment already cached(before harvester plugin added) and we have KeyError as result.

**Comment by amercader** [comment]
@smotornyuk can you send a PR with your fix?
