### ISSUE TITLE
Version number does not match repository tags

### ISSUE THREAD

**Issue by augusto-herrmann** [ckan/ckanext-harvest#231]
The version number declared in setup.py has always been 0.2. On the git repository, we've got tags for ckan-1.6, v0.0.1, v0.0.2, v0.0.3, and v0.0.4. In all of those the declared version number is 0.2.

This should probably be fixed in future tag versions by putting the appropriate version number in setup.py.

**Comment by davidread** [comment]
Looks like @amercader tagged the last four, mostly recently Dec 2015 - was this just an oversight or is something else at play here?

I would have thought this is mature enough to call it 1.0.0 now. I'm happy to update setup.py and adding a tag, if that's all needing doing? (Although not motivated enough to put it on PyPi - see discussion at https://github.com/ckan/ckanext-harvest/issues/149 )

**Comment by augusto-herrmann** [comment]
Really? We're still having a lot of trouble with it, especially when upgrading legacy data from earlier versions of this plugin and of CKAN.

**Comment by davidread** [comment]
Interesting - is the harvest model migration in not working right for you?
Do provide details in an issue. And if there are things we can do to
'upgrade' older CKAN datasets then it would be good to know.

**Comment by augusto-herrmann** [comment]
I'm not sure how the harvest model migration works. It's not documented in the README, and I was not aware of its existence until you mentioned it here. It seems to be based on [a couple of heuristics](https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/model/__init__.py#L74) on `model/__init__.py`, but I have no idea whether or not they were activated during our attempt to upgrade both CKAN and ckanext_harvest. I'll try to provide details in another issue, as it seems to be OT to the topic of discussion here.

Anyway, the versions mentioned there ("v2" and "v3") do not match any versioning system declared in `setup.py` or the repo tags, so I assume them to be a version number for the model, not for ckanext_harvest.

**Comment by metaodi** [comment]
In the meantime this issue has been resolved and proper versioning is used in setup.py and the tags.
