### ISSUE TITLE
harvest_job_list ridiculously slow

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckanext-harvest#232]
In our production we currently have about 550 harvest jobs and harvest object count is currently going at 280000. 

Since harvest_job_list fetches them all in https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/logic/action/get.py#L239
and dictize https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/logic/dictization.py#L37 filters them one by one, harvest_object table could use a index for harvest_job

for example CREATE INDEX harvest_job_id_index ON harvest_object(harvest_job_id)

In our production single dictize took 1.5 seconds before index and 1.5ms after index and this made possible to actually call harvest_job_list as nginx timeouted it at 2 minutes before index. After index it took only few seconds, which is reasonable as there are no public links for templates which use job_list.

**Comment by davidread** [comment]
Agreed, I'm seeing a significant speed increase as well with this index. Can you work out how to do a PR?

**Comment by Zharktas** [comment]
I could do PR soonish, haven't done DB migration scripts (most likely this will need it) but I will figure it out.

**Comment by davidread** [comment]
Super, thanks @Zharktas 

I guess it needs something added to setup.py https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/model/__init__.py#L44

along the lines of this stuff:
http://docs.sqlalchemy.org/en/latest/core/constraints.html#sqlalchemy.schema.Index.create

**Comment by Zharktas** [comment]
PR in #233

**Comment by davidread** [comment]
Thanks!

**Comment by avdata99** [comment]
I just proposed to add more indexes here: https://github.com/ckan/ckanext-harvest/pull/414
