### ISSUE TITLE
Dealing with confidential source configurations

### ISSUE THREAD

**Issue by torfsen** [ckan/ckanext-harvest#248]
I want to use a custom harvester to extract data from a database and upload it to CKAN. This works fine, but I am not sure how to store the configuration of the harvester source, since it contains the (confidential) database credentials.

A source's configuration seems to be available to the general public via the `harvest_source_show` API function, so I cannot put the information there. What is the best practice for this issue?

**Comment by davidread** [comment]
The general assumption has been that CKANs have open metadata, and therefore harvesting from public sources. I'm pretty sure that the openness of harvest sources is helpful in ushering obscure CSW servers into public locations, which is a useful API for people to use in itself. So I'm pretty hesitant to introduce any privacy to harvest sources.

You've got an interesting use case though. Your database is closed, but your CKAN is open - is that right? I wonder if it is a one-off or potentially wide-spread. If it was the former then I'd say just put the credentials in the ckan config and 1-line hack in your harvester code to get the credentials. But if you're arguing it could be more widespread then a better solution would be needed.

**Comment by torfsen** [comment]
Well, access to the database in general is closed, but some of the data it contains is open. It's a common pattern for us when we're harvesting data from internal sources (databases, FTP servers, ...). These original sources usually contain both closed and open data, or their data can only be made public after some aggregation (for example to avoid privacy issues). In addition, the authorization systems of the original sources often aren't fine-grained enough to create read-only accounts for specific parts of their data. However, I'm not sure how common this issue is for other users of ckanext-harvest.

Personally, I view harvesting source configurations as part of CKAN's management infrastructure rather than its (meta)data. For me they're similar to my CKAN configuration file, which also contains sensitive information and shouldn't be shared. But that's only my personal opinion and I do understand your arguments for public source configurations.

At the moment I don't think that this is an important issue, unless other users come forward with the same problem. I will think about how to handle this for us, and if the solution seems interesting for others I will report back.

**Comment by davidread** [comment]
Sounds fair enough.

I'm still intrigued that you have databases of *metadata* though. It's pretty common to have legacy databases with data, and use standard ETL to publish the data openly elsewhere, but this is the first time I've seen the dataset metadata stored there too.

**Comment by torfsen** [comment]
I'm not sure we're understanding each other correctly, so let me clarify.

 The database contains the original data. We use ckanext-harvest both for ETL (load the data from the database, aggregate it, export it to a file, upload the file to CKAN) and for associating the data with metadata. The latter is usually not explicitly stored in the database but either collected from the environment (e.g. timestamps for last modification dates) or hard-coded into the source configuration (e.g. static metadata like the responsible organization).

So we're hosting both the exported data and its metadata on CKAN.

**Comment by davidread** [comment]
Ah, got you - neat idea to use the harvester for ETL. I guess it's not surprising that the harvest framework doesn't provide everything you need, for this innovative use. It's seems a reasonable reason to allow private fields in the source config.

**Comment by torfsen** [comment]
I've come up with a solution that works for our use case. As I've said before I don't think that this issue is currently common enough to include support for it in ckanext-harvest, but I'm documenting it here in case other users run into the same problem.

The idea is to keep the confidential values in your CKAN configuration file (i.e. `production.ini`). This makes them more cumbersome to change (edit the file and restart CKAN vs. using the web interface), but in my experience harvest source configurations don't change that often (and you can still use the usual approach for non-sensitive settings).

To load the settings I use the following code:
```python
class MyHarvester(plugins.SingletonPlugin):

    def _set_config(self, source):
        self.public_config = json.loads(source.config)
        self.private_config = {}
        prefix = 'ckan.harvest.{}.'.format(source.url)
        for key, value in pylons.config.iteritems():
            if key.startswith(prefix):
                self.private_config[key[len(prefix):]] = value

    def gather_stage(self, harvest_job):
        self._set_config(harvest_job.source)
        log.info('Public setting: ' + self.public_config['some_public_setting'])
        log.info('Private setting: ' + self.private_config['some_private_setting'])
        ...

    (etc.)
```
In `production.ini`, I can then set any value via
```
ckan.harvest.my-harvest-source.some_private_setting = foo
ckan.harvest.my-harvest-source.another_private_setting = bar
```
Here, `my-harvest-source` is the source's URL suffix.

**Comment by davidread** [comment]
I like it 👍
