### ISSUE TITLE
What's the CKAN lastest version supported?

### ISSUE THREAD

**Issue by thenets** [ckan/ckanext-harvest#250]
Hi, I'm Luiz.

I'm trying to install the Harvest on CKAN but I'm getting too many errors.
What's the best version of CKAN, Jetty (or Tomcat), Redis, RabbitMQ and Python to use with Harvest? And what's the best OS?

Thanks a lot. I'm getting too many troubles with installation.

**Comment by davidread** [comment]
I think this is all covered more or less in the docs.

https://github.com/ckan/ckanext-harvest/blob/master/README.rst :
> This extension requires CKAN v2.0 or later
> sudo apt-get install redis-server
(which assumes you are on the recommended Ubuntu versions 12.04 or 14.04)

http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html
> Python	The Python programming language, v2.6 or 2.7
> sudo apt-get install python-dev solr-jetty
(which again assumes you are on the recommended Ubuntu versions 12.04 or 14.04)

Please use these versions and if you still have errors, please open an issue quoting the error.
