### ISSUE TITLE
CKAN Harvester Issue With Default Groups

### ISSUE THREAD

**Issue by nickajwill** [ckan/ckanext-harvest#253]
I've been trying to set up a CKAN installation for use as a Caribbean open data portal for a few weeks now but I've been running into challenges when I try to set up the CKAN Harvester and import some data sets. 

My issue has to do with me trying to set the "default_groups" parameter.

If I set it to an empty set like so --> "default_groups" : []

There are no issues.

But if I try to include groups like so ---> "default_groups" : ["trinidad-and-tobago"]

I get this error :

---

The form contains invalid entries:

Config: Error parsing the configuration options: default_groups must be a list of group names/ids (i.e. strings)

---

I've done my best to be thorough here but please feel free to ask me any additional questions for clarification. I'd be very grateful for any insight/help with figuring this out.

I posted a variation of this as a question on StackExchange here in case it helps in providing some context : http://opendata.stackexchange.com/questions/9063/ckan-harvester-issues

**Comment by davidread** [comment]
Nick, could you put in a print or log right before this exception:

**Comment by nick22891** [comment]
Hey @davidread - Thanks for pointing me in the right direction. I was able to edit the script to fix the issue (which cropped up in the import stage again after I fixed the validation issue). I submitted a pull request with my fix.

Cheers!

**Comment by metaodi** [comment]
This was fixed with #255
