### ISSUE TITLE
Simple way to refresh all data

### ISSUE THREAD

**Issue by thenets** [ckan/ckanext-harvest#259]
Hi, I'm Luiz.

I'm having some problems with the Harvest. I have imported all data, but I always need to check updates from CKAN sources and get data individually.

I want to know if can I run command to check updates and import any updated data.
For example:
```
$ harvester check_updates
$ harvester update_all_sources
```

Or something like that. Just like the Ubuntu's "apt-get". Two or three simple commands, like "apt-get update" and "apt-get upgrade".

For now, I'm doing this:
```
$ harvester job-all           # It's ok
$ harvester gather_consumer   # PROBLEM: Don't finish
$ harvester fetch_consumer    # PROBLEM: Don't finish
```

But I have a problem with it. The command don't finish at the end. I don't know why, but the command keep running. So I create a timer to kill the process. It's important to me the process finish at the end.

Thanks.

**Comment by davidread** [comment]
>  I don't know why, but the command keep running

It's a queue consumer - it's waiting for any more instructions. Like if someone creates a new job by pressing 'Refresh' in the web ui.

As the docs say, you should run these in the background on the server at all times.

If your use case doesn't allow jobs to be created for some reason, then consider adapting 'paster run_test' for your purposes.
