### ISSUE TITLE
Installing ckan harvest on docker image 

### ISSUE THREAD

**Issue by hhkaos** [ckan/ckanext-harvest#260]
I'm having some issues trying to make harvest work in docker.

Previously I followed [CKAN instructions](http://docs.ckan.org/en/ckan-2.4.3/maintaining/installing/install-using-docker.html#installing-ckan), and [yours](https://github.com/ckan/ckanext-harvest/blob/master/README.rst) after that. But then, when I run:
```
(default)root@2657865c8aeb:/usr/lib/ckan/default/src/ckanext-harvest# paster --plugin=ckanext-harvest harvester initdb --config=mysite.ini
Config file not found: /usr/lib/ckan/default/src/ckanext-harvest/mysite.ini
(Given by: -c parameter)
```

Should I have this **mysite.ini** somewhere?

I also tried:
```
cd /usr/lib/ckan/default/src/ckanext-harvest/ckanext/harvest/commands
python harvester.py initdb
```

But I got no answer, so I'm not sure I have the database initialised.

Anyway I tried to access to `localhost:5000` (I exposed that container's port before running `sudo docker run -d -p 80:80 -p 5000:5000 --link db:db --link solr:solr ckan/ckan`) but I get a refused connection, I guess that it is because Harverst is not running. How can I check/fix that?

![screen shot 2016-07-29 at 12 12 35](https://cloud.githubusercontent.com/assets/826965/17245222/cd94e2ca-5585-11e6-8374-bced28731b8e.png)

I added to my **/etc/ckan/default/ckan.ini** file:

````
[server:main]
use = egg:Paste#http
host = 0.0.0.0
port = 5000

[app:main]
use = egg:ckan
full_stack = true
cache_dir = /tmp/%(ckan.site_id)s/
beaker.session.key = ckan
...

# haverst
ckan.harvest.mq.type = redis
ckan.plugins = harvest ckan_harvester

## Site Settings
...
```

And then I restarted my container & apache.

----

I would also add some things to the documentation like:

1. `apt-get update` needed sometimes before `apt-get install redis-server`
2. CKAN configuration file location: /etc/ckan/default/ckan.ini (Ubuntu)
3. Be careful adding lines to the configuration file, do that after `[app:main]`
4. Before `pip install -e git+https://github.com/ckan/ckanext-harvest.git#egg=ckanext-harvest` be sure that you have Git installed: `sudo apt-get install git`
5. Before running `pip install -r pip-requirements.txt`go to folder `/usr/lib/ckan/default/src/ckanext-harvest/``

**Comment by davidread** [comment]
@hhkaos There are lots of useful things here that we can improve in the install doc - thanks for mentioning it all.

> paster --plugin=ckanext-harvest harvester initdb --config=mysite.ini

mysite.ini is your ckan config file. The default is: /etc/ckan/default/ckan.ini

> I tried to access to localhost:5000 but I get a refused connection

Ah, that port is for when running under 'paster serve', whereas the instructions are talking about running apache. That should be changed to `http://localhost/harvest`

> apt-get update needed sometimes before apt-get install redis-server

Yes could usefully add that. We have it in the main ckan 'install from package' instructions, so why not for extensions too.

> CKAN configuration file location: /etc/ckan/default/ckan.ini (Ubuntu)

Agreed, we should use that instead of mysite.ini everywhere

> Be careful adding lines to the configuration file, do that after [app:main]

Agreed

> Before pip install -e git+https://github.com/ckan/ckanext-harvest.git#egg=ckanext-harvest be sure that you have Git installed: sudo apt-get install git

This applies to all users that installed ckan by package. I wonder if we should just add that to the ckan package install instructions? It's needed to install all extensions afaik. What do people think?

> Before running pip install -r pip-requirements.txt go to folder /usr/lib/ckan/default/src/ckanext-harvest/`

Good point.

I've got a PR to cover all the points (apart from installing git, which is to be discussed): https://github.com/ckan/ckanext-harvest/pull/261 Please do comment on it to say if it appears to cover everything.

**Comment by hhkaos** [comment]
Thanks David!

I did it and it worked :)
```
(default)root@2657865c8aeb:/# paster --plugin=ckanext-harvest harvester initdb --config=/etc/ckan/default/ckan.ini

2016-07-29 12:18:28,384 DEBUG [ckanext.harvest.model] Harvest tables defined in memory
2016-07-29 12:18:28,985 DEBUG [ckanext.harvest.model] Harvest tables created
DB tables created
```

But I still can not access to **http://10.10.74.100/harvest** (it's a VPN, so it shouldn't work to you), I'm getting a 404. Do I need to configure apache?

This is the Apache error.log:
```
[Fri Jul 29 12:29:49.111477 2016] [mpm_event:notice] [pid 24:tid 140656821925760] AH00489: Apache/2.4.7 (Ubuntu) mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
[Fri Jul 29 12:29:49.111634 2016] [core:notice] [pid 24:tid 140656821925760] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[Fri Jul 29 12:29:53.151624 2016] [:error] [pid 49:tid 140656596993792] 2016-07-29 12:29:53,151 INFO  [ckan.controllers.api] Can't find logic function: harvest_log_list
[Fri Jul 29 12:29:53.152927 2016] [:error] [pid 49:tid 140656596993792] 2016-07-29 12:29:53,152 INFO  [ckan.lib.base]  /api/3/action/harvest_log_list render time 0.005 seconds
[Fri Jul 29 12:29:57.413100 2016] [:error] [pid 47:tid 140656605386496] 2016-07-29 12:29:57,412 INFO  [ckan.lib.base]  /harvest render time 0.017 seconds
[Fri Jul 29 12:29:59.420449 2016] [:error] [pid 47:tid 140656605386496] 2016-07-29 12:29:59,420 INFO  [ckan.lib.base]  /harvest render time 2.000 seconds
```

----

I have just checked your PR, it's perfect, thx! :)

**Comment by davidread** [comment]
Just check your ckan ini only has one line with "ckan.plugins".

Did you definitely restart apache2?

Do you get a response from /api/action/harvest_source_list ?

**Comment by hhkaos** [comment]
Touché! you are right, I didn't know that there were another **ckan.plugin** on line 106 ^_^'':
`ckan.plugins = stats text_view image_view recline_view`

I have modified it to: `ckan.plugins = stats text_view image_view recline_view harvest ckan_harvester` and now it's working, thx!

![screen shot 2016-07-29 at 17 36 58](https://cloud.githubusercontent.com/assets/826965/17253953/24b6604c-55b3-11e6-9894-315d89b5cf10.png)

Thank you very much David!

**Comment by davidread** [comment]
Great :)

Left to address now are:
* discuss whether to put git install instructions in the instructions for ckan package install or for every extension's readme
* get the PR merged

**Comment by hhkaos** [comment]
Hi David, sorry for taking so long to reply. I would add just a note as a reminder, or at least a recommendation to read the *ckan package install* before start following the instructions. I normally prefer instructions that go straight to the point :).

**Comment by davidread** [comment]
I've made a PR for the package install instructions: https://github.com/ckan/ckan/pull/3201

**Comment by davidread** [comment]
Both PRs are now merged. Closing.
