### ISSUE TITLE
Swedish translations ?

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckanext-harvest#266]
The repository has only swedish translations https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/i18n/sv/LC_MESSAGES/ckanext-harvest.po.

There are some terms that conflict with base ckan terms, for example Datasets, which results to that changing translation in instance is harder since we have to change it in two different places.

Should there be translations at all or should there be translations for all the languages that base ckan supports ?

**Comment by amercader** [comment]
There should be as many translations as possible, that is as many as users have contributed :)

Please submit any new languages to https://www.transifex.com/okfn/ckanext-harvest/dashboard/ and we'll definitely add them to the main repo.

The issue that you mention about strings clashing with core ones is a worrying one. I guess that the [current process](http://docs.ckan.org/en/latest/extensions/translating-extensions.html) does not take into account existing strings in core. If there is any way to improve it to avoid duplicates we'll definitely add it, but I suspect that the only way would be a separate script that checks for duplicates.

**Comment by metaodi** [comment]
I think the issue with the clashing strings can be avoided by a) using a seperate text domain b) use the [`ITranslation` interface](http://docs.ckan.org/en/latest/extensions/translating-extensions.html).
