### ISSUE TITLE
Document changes between releases

### ISSUE THREAD

**Issue by raphaelstolt** [ckan/ckanext-harvest#267]
Please start documenting changes between releases either in a changelog file or via GitHub release notes. Makes it much easier to track changes.

To save time on your end, make adding the changes to the changelog file a contribution requirement.

**Comment by amercader** [comment]
That sounds very reasonable. We always try to make all changes backwards compatible but we obviously might have missed something. Did you find any issue in particular while upgrading that you'd like to see documented?

**Comment by raphaelstolt** [comment]
Nah nothing particular as I've not upgraded yet, but had to use GitHub [compare](https://github.com/ckan/ckanext-harvest/compare/v0.0.3...v0.0.4) links to skim through the changes; which isn't that comfortable.

**Comment by torfsen** [comment]
I strongly suggest following the conventions of [Keep a CHANGELOG](http://keepachangelog.com/).
