### ISSUE TITLE
ckan-harvest

### ISSUE THREAD

**Issue by tinklem** [ckan/ckanext-harvest#279]
i have installed ckan and ckan-harvest extension by using this link https://github.com/ckan/ckanext-harvest
after installing harvest i am not able to add sources , can any one help on this issue as when i am using harvester command its saying command not found but i have checked the path of the command and code for the .py file its there and code is perfectly fine, what could be the issue .

please help

**Comment by davidread** [comment]
This sounds like you need help, rather than it being an issue with the code.

Please post full details to stackoverflow with tag #ckan instead.

**Comment by tinklem** [comment]
I am harvesting data from ckan instance and collecting in an other ckan instance. I am totally new to this subject. Though I am able to harvest datasets in my ckan instance, but I am not able to understand the next step, how to pretreatment and postreatment of data, what should be my next step? Here is the screenshot of my current collection of datasets
![capture](https://cloud.githubusercontent.com/assets/25142517/22364294/7ff71e98-e496-11e6-8388-0b305cc4ac39.PNG)

Please suggest me how to go about it
