### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by torfsen** [ckan/ckanext-harvest#284]
It's been almost a year since the [release of v0.0.5](https://github.com/ckan/ckanext-harvest/releases/tag/v0.0.5), and [a lot of commits have been made since then](https://github.com/ckan/ckanext-harvest/compare/v0.0.5...master). It would therefore be nice to have a new release.

While we're at it, I also suggest that ckanext-harvest starts using [semantic versioning](http://semver.org/) to make it easier to recognize the amount of changes in a release. In addition, changes should be properly documented (see #267).

**Comment by amercader** [comment]
@torfsen The issue with this and the [other extensions](https://github.com/ckan/ckanext-pages/issues/49) is lack of maintainers that can do a proper releasing and tracking of the changes. We are already spread very thin so releases tend to be done in an "as needed" basis, which I agree is not ideal.

If you (or anyone else) wants to step up and help maintain any of the official extensions that would help a lot.

**Comment by torfsen** [comment]
@amercader I understand that completely. Unfortunately while we do use *ckanext-harvest* we're nowhere close to the heavy usage of other users. I'm therefore a bit reluctant to take over responsibility for such a central piece of the greater CKAN architecture that I have only little experience with. *ckanext-pages*, on the other hand, is neither as complex nor as "mission critical" as *ckanext-harvest*, so if it helps I gladly offer to maintain that. It's not much but maybe a start :wink:

**Comment by metaodi** [comment]
@amercader I could certainly help maintaining ckanext-harvest. I already have that "role" for ckanext-pages, but I stopped using it (which automatically reduces the motivation of actively maintaining it). But I'd say I'm one of the heavy users of this extension, so this would make sense.

**Comment by amercader** [comment]
That's great @metaodi! You should have write access now. If you have the chance it would be great to start with a new release as @torsfen suggested

**Comment by metaodi** [comment]
I just added #285 to start to properly document the changes of each release. I propose to start the new "semantic versioning" releases by releasing 1.0.0, then we can take it from there.

Any opinions about that?

According to semver.org
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

So I think this does no longer fit, as we try our best to be backwards compatible and the "initial development" has already happend.

**Comment by amercader** [comment]
Sounds good @metaodi

**Comment by metaodi** [comment]
ckanext-harvest 1.0.0 has been released :wink:

**Comment by amercader** [comment]
Woo, thanks @metaodi! :tada:
