### ISSUE TITLE
Pull in settings from Environment Variables

### ISSUE THREAD

**Issue by LondonAppDev** [ckan/ckanext-harvest#287]
It would be really useful to be able to set the settings using environment variables.

In particular, the redis host, port and db.

Would you be open to this change if I made a PR for it?

**Comment by LondonAppDev** [comment]
To elaborate on why. I am trying to run the CKAN harvest processes in Docker containers. Currently, I need to update the `production.ini` file manually in order to set the redis details.

**Comment by polarp** [comment]
@LondonAppDev There is an existing extension if you want to achieve this.
Take a look at this [repository](https://github.com/okfn/ckanext-envvars)

**Comment by amercader** [comment]
@LondonAppDev yes, try and give ckanext-envvars a go

**Comment by LondonAppDev** [comment]
Tried it and it works like a charm. Thank you for the recommendation.
