### ISSUE TITLE
Error using default_extras

### ISSUE THREAD

**Issue by etj** [ckan/ckanext-harvest#289]
See also #249.
When a ``default_extras`` is set, but there's no extra in the remote dataset, extras is init'ted as a dict and not as a list (currently here's the line, but may not be there in the future: https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/harvesters/ckanharvester.py#L527)
This will cause a log line like this:
```
DEBUG [ckanext.harvest.model] 'dict' object has no attribute 'append'
```
and the dataset will not be imported.

**Comment by metaodi** [comment]
This was fixed with #290
