### ISSUE TITLE
_last_error_free_job could be moved to HarvesterBase

### ISSUE THREAD

**Issue by knudmoeller** [ckan/ckanext-harvest#302]
CKANHarvester._last_error_free_job() is a useful method, not just for a CKAN harvester, but for any kind of harvester (like the spatial one I'm working on). Looking at the code, there seems to be no reason why it shouldn't be in HarvesterBase. Would it be possible to move it?

**Comment by metaodi** [comment]
@knudmoeller I don't see any reason why this could not be in HarvesterBase. But then I would remove the underscore at the beginning, as this would then become part of the API of HarvesterBase (rather then an internal method). Could you create a PR with this change?

**Comment by knudmoeller** [comment]
Cool, I'll get on to it right away!

**Comment by knudmoeller** [comment]
Here it is: https://github.com/ckan/ckanext-harvest/pull/305

**Comment by metaodi** [comment]
Merged in #305
