### ISSUE TITLE
Does CKAN track who has accessed what resources on CKAN?

### ISSUE THREAD

**Issue by ply112** [ckan/ckanext-harvest#308]
We plan to upload PHI data to our CKAN instance.  Although we have already set these datasets as PRIVATE, it would be important and it is a corporate requirement to track who has accessed what datasets/resources and the type of access (download / view etc. ).  I am digging deep into CKAN's database tables, including tracking_summary, tracking_raw, resource_view, activity, activity_detail etc., but haven't been able to pinpoint the exact table that contains the right information.  

So far, the tracking_raw table seems to have the information I need.  However, the user_key column does not match the user id column in the ldap_user or user table.  Additionally, the same user_key is linked to activities by different users within a short time window. In essence, I am still unable to figure out who has accessed what. 

Any inputs would be greatly appreciated.  Thanks.

**Comment by CarlQLange** [comment]
This is probably better to add to the https://github.com/ckan/ckan repo or sending to the mailing list - this repository is for a subproject.
