### ISSUE TITLE
Clear does not remove datasets from index

### ISSUE THREAD

**Issue by metaodi** [ckan/ckanext-harvest#309]
After a clear on a harvest source has been done, the packages remain in the solr index which can lead to errors and is confusing for users.
I propose to call `ckan.lib.search.clear` on each dataset that has been cleared by the "Clear" command.

This potentially increases the time needed for a "clear" but would leave the CKAN instance in a more consistent state.

WDYT? I would be happy to provide a PR for this.

**Comment by amercader** [comment]
Do we have a way of knowing the individual datasets deleted by the clear command? IIRC correctly it's a big sql statement executed directly.

Perhaps we can run a single Solr delete query filtering by `harvest_source_id` (which should be indexed as a dataset extra), using the solr client library.

**Comment by metaodi** [comment]
I just checked the source, and we already have [`harvest_source_index_clear`](https://github.com/ckan/ckanext-harvest/blob/95d0c1ca419c483cf06821203b1d319dd03c7319/ckanext/harvest/logic/action/update.py#L295-L339) which is [called in `harvest_source_clear`](https://github.com/ckan/ckanext-harvest/blob/95d0c1ca419c483cf06821203b1d319dd03c7319/ckanext/harvest/logic/action/update.py#L107), so theoretically we already have what you proposed @amercader .

Now I just have to find out, why this does not work on my instance :wink:

**Comment by metaodi** [comment]
I just found out, that after I harvested (using a custom harvester based on this extension) the datasets would not have the `harvest_source_id` attribute set. But it is set if I rebuild the solr index. The `harvest_source_id` attribute is added in the `after_show` of this extension.

After some digging I found this [odd comment in the source](https://github.com/ckan/ckanext-harvest/blob/0918a9a3415b171037ca1d6f462503d5d6a50664/ckanext/harvest/harvesters/base.py#L351-L357):

```python
# Defer constraints and flush so the dataset can be indexed with
# the harvest object id (on the after_show hook from the harvester
# plugin)
harvest_object.add()
 
model.Session.execute('SET CONSTRAINTS harvest_object_package_id_fkey DEFERRED')
model.Session.flush()
```

So probably I need to do the same thing in my custom harvester.

**Comment by CarlQLange** [comment]
Oh, hey, I have this too, thanks for the info @metaodi!

**Comment by amercader** [comment]
Did these commands did the trick @metaodi @CarlQLange ? Can this be closed?

**Comment by CarlQLange** [comment]
I haven't tested yet. btw @amercader the harvester I'm having issue with is a geminiharvester from ckanext-spatial. will update you when I get to check it out in like a week

**Comment by metaodi** [comment]
It worked with the above code.
