### ISSUE TITLE
Does CKAN keep track of who has viewed or downloaded a resource?

### ISSUE THREAD

**Issue by ply112** [ckan/ckanext-harvest#310]
For audit purposes, I would like know if CKAN keeps track of user access of data files, such as who has viewed or downloaded a data file.  If yes, where is this information kept?  I have explored the tracking_raw table, but it doesn't tell you who has accessed the resources.  

Thanks,
P Y

**Comment by CarlQLange** [comment]
This is probably better to add to the https://github.com/ckan/ckan repo or sending to the mailing list - this repository is for a subproject.
