### ISSUE TITLE
How to set harvesting stages when using Open search

### ISSUE THREAD

**Issue by davv-deimos** [ckan/ckanext-harvest#314]
Hi all,
I don't know if this is the right place to ask this kind of questions, but I'll give it a try anyway.

I just read the README file, which uses CSW servers as an example on how to organize the harvesting process.
I would like to know your opinion on how should I write my harvesting process, considering that I'm querying Open Search servers. 

In the given example (CSW server), all that the gather stage does is getting a list of all the records that exist, and afterwards the fetch stage proceeds to retrieve the contents of each remote object. However, when using Open Search, a query such as (https://scihub.copernicus.eu/dhus/search?q=* )already gives all the information about each record/entry.

What do you think are the implications of this? Should I set just 2 stages such as gather and import instead of using all 3 stages?

Thank you in advance.

**Comment by metaodi** [comment]
This happens in many situations, take for instance the CKAN harvester in this extension, it does [nothing in the `fetch_stage`](https://github.com/ckan/ckanext-harvest/blob/0918a9a3415b171037ca1d6f462503d5d6a50664/ckanext/harvest/harvesters/ckanharvester.py#L353-L356):

```python
def fetch_stage(self, harvest_object):
    # Nothing to do here - we got the package dict in the search in the
    # gather stage
    return True
```

So if you can save all information in the gather stage, simply return `True` in the fetch stage and continue with the import stage.

Hope this helps.

**Comment by davv-deimos** [comment]
Thank you for your answer :) 
This was more of a sanity check, since this is the way we are doing it over here. But I was given this code to maintain without being involved in its development, so I wanted to be sure that it made sense.
