### ISSUE TITLE
[ckanext.harvest.model] Instance is not bound to a Session

### ISSUE THREAD

**Issue by MaciejJanowski** [ckan/ckanext-harvest#317]
I just installed the new release of CKAN (2.7.3) and encountered such error 
```
INFO  [ckanext.harvest.queue] Received harvest object id: fd026470-dd37-408f-9b57-e819c52f70bf
DEBUG [ckanext.harvest.harvesters.ckanharvester] In CKANHarvester import_stage
DEBUG [ckanext.harvest.model] Instance <User at 0x7f70731823d0> is not bound to a Session; attribute refresh operation cannot proceed
```
I followed the whole process of installing ckan, datastore, datapusher and harvester. 
I am trying to harvest: https://data.smartdublin.ie/.
I tested different sources and the same error occurs. Please advise me what I did wrong or what shall I do to make everything work properly.

**Comment by metaodi** [comment]
Please see issue #151, which describes the same issue with several possible solution. There is currently also a PR underway (#312) to address this issue as well.

I'm closing this as it's a duplicate.
