### ISSUE TITLE
Possibility to make the append_type parameter used in _gen_new_name configurable

### ISSUE THREAD

**Issue by seitenbau-govdata** [ckan/ckanext-harvest#326]
We needed the possibility to set the append_type parameter used in _gen_new_name globally for all harvesters within the CKAN config. So the default type can be changed easily by setting it in the config without the need changing the source code.

We have already made the changes locally in our installation. If you are interested to add the possibility in your repository we enjoy creating a pull-request.

**Comment by metaodi** [comment]
What is the append_type? The current implementation has no such parameter as far as I can tell. Maybe you can link to your implementation or create a PR so we can discuss the changes there.

I believe it could be interesting to have configuration to influence the generation of package names, so I'd like to know more about your solution.

**Comment by seitenbau-govdata** [comment]
And here is the PR #327

**Comment by seitenbau-govdata** [comment]
Closed, PR #327 merged.
