### ISSUE TITLE
Cannot harvest from GeoNode CSW

### ISSUE THREAD

**Issue by frafra** [ckan/ckanext-harvest#364]
Here's the error I get on every dataset: `Element '{http://www.isotc211.org/2005/gmd}name': This element is not expected. Expected is ( {http://www.isotc211.org/2005/gmd}title ).`

Full page: [Job Report - geonode-testing - NINA catalog.zip](https://github.com/ckan/ckanext-harvest/files/3223964/Job.Report.-.geonode-testing.-.NINA.catalog.zip)

**Comment by frafra** [comment]
[Job Report - geonode-testing - NINA catalog.zip](https://github.com/ckan/ckanext-harvest/files/3223964/Job.Report.-.geonode-testing.-.NINA.catalog.zip)

**Comment by davidread** [comment]
Afaict there is no CSW harvester in ckanext-harvest. Are you using one of these?:
* https://github.com/geosolutions-it/ckanext-geonode
* https://github.com/ckan/ckanext-spatial/blob/master/ckanext/spatial/harvesters/csw.py
* https://github.com/datagovuk/ckanext-spatial/blob/dgu/ckanext/spatial/harvesters/csw.py

They all vary in how they do validation. This error is saying that it is using gmx.xsd to do a standard XSD validation, and it expected a `<gmd:name>` tag first, but it got the `<gmd:title>`. Order matters in ISO19139, well if you are following the letter of the standard...

There are a few different versions of gmx.xsd floating around which you could try. And find out exactly what spec the GeoNode data is expressed as - they may recommend a particular validator you could use instead.

Closing, as this is not an error with ckanext-harvest - feel free to open the issue on the repo you're using for CSW harvesting.

**Comment by frafra** [comment]
Yes, I am using the second one. Thanks for your help :)
