### ISSUE TITLE
`test_default_extras` is broken

### ISSUE THREAD

**Issue by metaodi** [ckan/ckanext-harvest#369]
Using the current ckan `master` the following test is broken:

https://github.com/ckan/ckanext-harvest/blob/ecf578648bee3488f901ba359eaec15209daedfc/ckanext/harvest/tests/harvesters/test_ckanharvester.py#L306-L329

I need to further analyze this and already opened a WIP PR #368.

Any help is appreciated (cc @amercader)

**Comment by metaodi** [comment]
@amercader I already have a PR to fix the imports: #358

**Comment by amercader** [comment]
I tracked this down the Harvest DB log code in here: https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/log.py#L14

This is causing recursion errors against ckan master (2.9). After disabling it the tests pass again.
