### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by roll** [ckan/ckanext-harvest#378]
Hi, the latest release had been done on Nov 1st, 2018. 

Any plans to release latest changes?

cc @amercader

**Comment by amercader** [comment]
Yes, I was actually preparing a release last week but got stuck trying to fix the tests. I'll do it next week

**Comment by amercader** [comment]
Done. 1.2.0 is out. Check the changelog if you are interested: https://github.com/ckan/ckanext-harvest/blob/master/CHANGELOG.rst
