### ISSUE TITLE
Incompatibility with ckan 2.8.5 ?

### ISSUE THREAD

**Issue by jeanpommier** [ckan/ckanext-harvest#411]
When upgrading to ckan 2.8.5, I get some weird extras fields on harvested datasets. See issue https://github.com/ckan/ckan/issues/5549

The 3 extra fields automatically added by ckanext-harvest ( https://github.com/ckan/ckanext-harvest/blob/master/ckanext/harvest/plugin/__init__.py#L95 ) are stored in a wrong way (value and key are separate lines in the list):

![image](https://user-images.githubusercontent.com/4491521/90623399-b1e5b280-e216-11ea-9350-ec853f9f16cb.png)

Have anyone met this ?

**Comment by amercader** [comment]
For reference, this will be fixed by https://github.com/ckan/ckan/pull/5546
