### ISSUE TITLE
Error rendering notification emails

### ISSUE THREAD

**Issue by avdata99** [ckan/ckanext-harvest#415]
When a harvest job finishes and we try to prepare (`toolkit.render`) an email to send

<pre><code class="python">
def prepare_error_mail(context, source_id, status):
    extra_vars = get_mail_extra_vars(context, source_id, status)
    body = <b>toolkit.render</b>('emails/error_email.txt', extra_vars)
    subject = '{} - Harvesting Job - Error Notification'\
              .format(config.get('ckan.site_title'))
</code></pre>

We have an error trying to read `session` information

<pre><code class="python">
    allow_cache = True
    # Force cache or not if explicit.
    if cache_force is not None:
        allow_cache = cache_force
    # Do not allow caching of pages for logged in users/flash messages etc.
    elif <b>session.last_accessed</b>:
        allow_cache = False
    # Tests etc.
</code></pre>

The error is `TypeError: No object (name: session) has been registered for this thread`

Error detail:

```
File "/usr/lib/ckan-new/src/ckanext-harvest/ckanext/harvest/logic/action/update.py", line 756, in prepare_error_mail
    body = toolkit.render('emails/error_email.txt', extra_vars)
  File "/usr/lib/ckan-new/src/ckan/ckan/lib/base.py", line 124, in render
    *pargs, **kwargs)
  File "/usr/lib/ckan-new/src/ckan/ckan/lib/base.py", line 186, in _pylons_prepare_renderer
    elif session.last_accessed:
  File "/usr/lib/ckan/lib/python2.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/lib/ckan/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
    return getattr(self._current_obj(), attr)
  File "/usr/lib/ckan/lib/python2.7/site-packages/paste/registry.py", line 197, in _current_obj
    'thread' % self.____name__)
TypeError: No object (name: session) has been registered for this thread
```

A conversation in gitter was started here: https://gitter.im/ckan/chat?at=5f64a49cf969413294f31813
It seems that `toolkit.render` do several more thing than just draw a template.
Should we use `jinja2` in this context and stop using `template.render`?

**Comment by amercader** [comment]
@avdata99 I assume that this process is started outside of the context of a web request, eg a background job or paster command. In that case yes, perhaps it will be easier to use jinja2 directly. But if the templates use some CKAN-specific features like `{% ckan_extends %}` or `{% resource %}` you'll have to load the necessary extensions as well (I don't think you'll need it)

**Comment by avdata99** [comment]
I created #416 for this @amercader.
