### ISSUE TITLE
Problem with other types of harvesters, besides 'ckan_harvester'

### ISSUE THREAD

**Issue by EvgeniaPatsoni** [ckan/ckanext-harvest#448]
I have installed CKAN v2.9.3 with Docker Compose and also installed the `ckanext-harvest` extension.
As mentioned in the documentation, I modified the configuration `.ini` file to include the harvest main plugin, as well as the harvester for CKAN instances: `ckan.plugins = harvest ckan_harvester`.

Everything works great up to this point an I can create a Harvest Source from my CKAN web ui.

However, I also need to use other types of harvesters, e.g `waf_harvester`.
As mentioned here: https://docs.ckan.org/projects/ckanext-spatial/en/latest/harvesters.html, I updated my configuration `.ini` file to look like this: `ckan.plugins = harvest ckan_harvester waf_harvester`.

Unfortunately, when I restart my ckan container (`docker-compose restart ckan`), it fails to start. The same thing happens with other harvesters as well e.g. `csw_harvester` and `doc_harvester`.

If I remove these harvesters from my `.ini` file and leave only the `ckan_harvester` the container gets back up again.

Any ideas what is causing this issue?

Thanks

**Comment by seitenbau-govdata** [comment]
Hi @EvgeniaPatsoni Have you installed the `ckanext-spatial` and activated the plugin `spatial` by adding it to the CKAN configuration ini file (according to the other CKAN plugins)?
Please try the following: `ckan.plugins = harvest ckan_harvester spatial waf_harvester`

**Comment by seitenbau-govdata** [comment]
I have seen that `spatial` isn't the plugin for `ckanext-spatial`, it is the plugin for the spatial paster command.

Please let us know what kind of error message is shown in the log file. Maybe that can help us to find the cause.

**Comment by EvgeniaPatsoni** [comment]
Thanks for your reply. 

No I did not install `ckanext-spatial` or activated the `spatial` plugin. I thought that only `ckanext-harvest` was necessary.
So should I install `ckanext-spatial` and try again?

Here is a part of the ckan logs. As you can see I get a `PluginNotFoundException` for `waf_harvester`.

```
2021-07-06 08:31:49,138 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/venv/src/ckan/ckan/templates
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/local/bin/ckan", line 11, in <module>
ckan          |     load_entry_point('ckan', 'console_scripts', 'ckan')()
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 829, in __call__
ckan          |     return self.main(*args, **kwargs)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 781, in main
ckan          |     with self.make_context(prog_name, args, **extra) as ctx:
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 700, in make_context
ckan          |     self.parse_args(ctx, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1212, in parse_args
ckan          |     rest = Command.parse_args(self, ctx, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1048, in parse_args
ckan          |     value, args = param.handle_parse_result(ctx, opts, args)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 1630, in handle_parse_result
ckan          |     value = invoke_param_callback(self.callback, ctx, self, value)
ckan          |   File "/usr/lib/ckan/venv/local/lib/python2.7/site-packages/click/core.py", line 123, in invoke_param_callback
ckan          |     return callback(ctx, param, value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 102, in _init_ckan_config
ckan          |     ctx.obj = CkanCommand(value)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/cli/cli.py", line 52, in __init__
ckan          |     self.app = make_app(self.config)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
ckan          |     load_environment(conf)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/config/environment.py", line 123, in load_environment
ckan          |     p.load_all()
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 165, in load_all
ckan          |     load(*plugins)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 179, in load
ckan          |     service = _get_service(plugin)
ckan          |   File "/usr/lib/ckan/venv/src/ckan/ckan/plugins/core.py", line 282, in _get_service
ckan          |     raise PluginNotFoundException(plugin_name)
ckan          | ckan.plugins.core.PluginNotFoundException: waf_harvester
ckan          | db:5432 - accepting connections
ckan          | /usr/lib/ckan/venv/local/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
ckan          |   from cryptography import x509
```

**Comment by seitenbau-govdata** [comment]
Yes, please install the `ckanext-spatial` in the same way as the `ckanext-harvest`. Then it should be working.

**Comment by seitenbau-govdata** [comment]
@EvgeniaPatsoni It works now?

**Comment by EvgeniaPatsoni** [comment]
Yes thank you that worked
