### ISSUE TITLE
"harvest" user hardcoded on CKAN harvested

### ISSUE THREAD

**Issue by amercader** [ckan/ckanext-harvest#45]
According to the docs you no longer need to create a "harvest" user, but that is no the truth for the CKAN harvester.

**Comment by metaodi** [comment]
This is no longer the case, since we have [`_get_user_name()`](https://github.com/ckan/ckanext-harvest/blob/cc438786de5010ed790a5596696edef374dc8091/ckanext/harvest/harvesters/base.py#L157). So harvest is still used if it's there, otherwise the `get_site_user` is called to return the correct user.
