### ISSUE TITLE
Release with 2.11 support?

### ISSUE THREAD

**Issue by Markus92** [ckan/ckanext-harvest#555]
I was kinda wondering if a release of an updated version of this extension was planned any time soon? It seems there's some commits related to CKAN 2.11 support, but the latest release pre-dates that by quite a bit. Is there any release planned in the short term?

**Comment by ThrawnCA** [comment]
Version 1.6.0 adds CKAN 2.11 support.

**Comment by Markus92** [comment]
Update is released
