### ISSUE TITLE
CKAN harvester bugged with relative links

### ISSUE THREAD

**Issue by volpino** [ckan/ckanext-harvest#8]
I tried the harvester on this CKAN instance http://dati.toscana.it but it retrives useless data for datasets like this http://dati.toscana.it/api/rest/dataset/arte-e-cultura/resource/8912d987-7f6b-48a0-b376-4613bb8e7905

As you can see the csv file is local on CKAN and has a relative path.
```"url": "/it/storage/f/2012-07-26T160139/intoscana-arte-e-cultura.csv",```
The harvester just copies the relative path but doesn't copy the actual file so the relative link won't work.

**Comment by davidread** [comment]
Closing as the storage controller (which this bug relates to) has been deprecated for some time now.
