### ISSUE TITLE
enable public access to job harvest reports 

### ISSUE THREAD

**Issue by gbinal** [ckan/ckanext-harvest#93]
I'm trying to dig into how to retain the permissions for harvest edting and administration while opening up the job reports (specifically the error reports) to viewing by any visitor, including non-account holders.  Sorry if I'm missing anything in the documentation (I looked!) but if it's not there, it'd be great to be able to customize this.

**Comment by davidread** [comment]
Closing as this is old and interest appears to have subsided. Reopen if this is still burning.
